[package]
name = "zettarium"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = {version = "0.4.41", features = ["serde"]}
clap = {version = "4.5.39", features = ["derive"]}
serde = {version = "1.0.219", features = ["derive"]}
serde_yaml = "0.9.34"
thiserror = "2.0.12"
